# Generated by Django 4.2.4 on 2023-09-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='price_bought',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='tracking_id',
            field=models.UUIDField(blank=True, editable=False, unique=True),
        ),
    ]
