# Generated by Django 4.2.4 on 2023-09-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='tracking_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
