# Generated by Django 4.2.4 on 2023-10-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'cod'), ('mobile', 'mobile')], default='mobile', max_length=50),
        ),
    ]
