# Generated by Django 4.2.4 on 2023-11-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_alter_consumer_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('paid', 'paid'), ('cod', 'cod'), ('delivered', 'delivered'), ('dispatched', 'dispatched')], default='cart', max_length=30),
        ),
    ]
