# Generated by Django 4.2.4 on 2023-09-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_alter_orderedproduct_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='courier_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='order_total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
