# Generated by Django 4.2.4 on 2023-08-27 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_wishlist_orderedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='consumer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_consumer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
