# Generated by Django 4.2.4 on 2023-09-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_orderedproduct_courier_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='coupon_bdt',
            field=models.IntegerField(default=0),
        ),
    ]
