# Generated by Django 4.2.4 on 2023-11-11 06:58

from django.db import migrations, models
import django.utils.timezone
import userAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_alter_orderedproduct_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref', models.UUIDField()),
                ('last_visit', userAPI.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
