# Generated by Django 4.2.4 on 2023-09-11 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_alter_orderedproduct_consumer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='price_bought',
            new_name='per_price',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_consumer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_consumer', to=settings.AUTH_USER_MODEL),
        ),
    ]
