# Generated by Django 4.2.4 on 2023-08-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsAPI', '0002_remove_wishlist_product_delete_orderedproduct_and_more'),
        ('userAPI', '0004_wishlist_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_product', to='productsAPI.product'),
        ),
    ]
