# Generated by Django 4.2.4 on 2023-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_rename_price_bought_orderedproduct_per_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
