# Generated by Django 4.2.4 on 2023-08-28 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='consumer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_consumer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
