# Generated by Django 4.2.4 on 2023-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_alter_orderedproduct_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='tracking_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
