# Generated by Django 4.2.4 on 2023-09-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='consumer_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='consumer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='consumer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='consumer_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='inside_dhaka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'cod'), ('mobile', 'mobile')], default='cod', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
