# Generated by Django 4.2.4 on 2023-09-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_orderedproduct_consumer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='reward_discount',
            field=models.IntegerField(default=0),
        ),
    ]
