# Generated by Django 4.2.4 on 2023-08-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_orderedproduct_consumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='quantity',
            new_name='ordered_quantity',
        ),
    ]
