# Generated by Django 4.2.4 on 2023-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0007_orderedproduct_reward_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPackageTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(editable=False)),
            ],
        ),
    ]
