# Generated by Django 4.2.4 on 2023-08-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0007_rename_quantity_orderedproduct_ordered_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('delivered', 'delivered')], default='unpaid', max_length=30),
        ),
    ]
