# Generated by Django 4.2.4 on 2023-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0009_remove_orderedproduct_used_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('paid', 'paid'), ('unpaid', 'unpaid'), ('delivered', 'delivered')], default='cart', max_length=30),
        ),
    ]
