# Generated by Django 4.2.4 on 2023-09-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
