# Generated by Django 4.2.4 on 2023-10-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='admin_roles',
            field=models.JSONField(default=dict),
        ),
    ]
