# Generated by Django 4.2.4 on 2023-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='coupon_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='max_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
