# Generated by Django 4.2.4 on 2023-08-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='phone_number',
            field=models.BigIntegerField(blank=True),
        ),
    ]
