# Generated by Django 4.2.4 on 2023-10-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0003_alter_moderator_admin_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='admin_roles',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
