# Generated by Django 4.2.4 on 2023-09-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0004_rename_rewards_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_dhaka', models.IntegerField(default=0)),
                ('outside_dhaka', models.IntegerField(default=0)),
                ('courier_fee', models.IntegerField(default=0)),
            ],
        ),
    ]
