# Generated by Django 4.2.4 on 2023-09-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0005_extrapayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrapayment',
            name='courier_fee',
        ),
    ]
