# Generated by Django 4.2.4 on 2023-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0006_remove_extrapayment_courier_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('book_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
