# Generated by Django 4.2.4 on 2023-09-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0007_bookedcalls'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='max_amount',
            field=models.IntegerField(default=0),
        ),
    ]
