# Generated by Django 4.2.4 on 2023-09-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0008_reward_max_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='discount',
            new_name='discount_bdt',
        ),
        migrations.RenameField(
            model_name='couponcode',
            old_name='max_discount',
            new_name='min_price',
        ),
    ]
