from django.urls import path
from .views import (
    ConsumerRegistrationView,
    WishlistSerializerAPI,
    ProfileAPI,
    OrderProductAPI,
    OrderProductCODAPI,
    OrderProductMobileAPI,
    CartAPI,
    PaymentLinkAPI,
)

urlpatterns = [
    path(
        "registration/",
        ConsumerRegistrationView.as_view(),
        name="registration_consumer",
    ),
    path(
        "wishlist/",
        WishlistSerializerAPI.as_view(),
        name="wishlist",
    ),
    path(
        "wishlist/<int:product_id>",
        WishlistSerializerAPI.as_view(),
        name="wishlist",
    ),
    path(
        "profile/",
        ProfileAPI.as_view(),
        name="profile_info",
    ),
    path(
        "cart/",
        CartAPI.as_view(),
        name="cart_products",
    ),
    path(
        "cart/<int:product_id>",
        CartAPI.as_view(),
        name="cart_products",
    ),
    # Order Products
    path(
        "ordered_product/",
        OrderProductAPI.as_view(),
        name="ordered_products",
    ),
    path(
        "ordered_product/cod",
        OrderProductCODAPI.as_view(),
        name="ordered_products_cod",
    ),
    path(
        "ordered_product/mobile",
        OrderProductMobileAPI.as_view(),
        name="ordered_products",
    ),
    path(
        "make_payment/",
        PaymentLinkAPI.as_view(),
        name="make_payment",
    ),
]
