# Generated by Django 4.2.4 on 2023-08-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderedProduct',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
