# Generated by Django 4.2.4 on 2023-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsAPI', '0005_remove_product_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_cad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_eur',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_gbp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(default=0),
        ),
    ]
