# Generated by Django 4.2.4 on 2023-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsAPI', '0006_alter_product_price_cad_alter_product_price_eur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_bdt',
            new_name='discount_max_bdt',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
