# Generated by Django 4.2.4 on 2023-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('total_received_money', models.IntegerField(default=0)),
            ],
        ),
    ]
